/* confdefs.h */
#define PACKAGE_NAME "freeswitch"
#define PACKAGE_TARNAME "freeswitch"
#define PACKAGE_VERSION "1.10.8-release"
#define PACKAGE_STRING "freeswitch 1.10.8-release"
#define PACKAGE_BUGREPORT "bugs@freeswitch.org"
#define PACKAGE_URL ""
#define PACKAGE "freeswitch"
#define VERSION "1.10.8-release"
#define SWITCH_MOD_DIR "/usr/local/freeswitch/mod"
#define SWITCH_RUN_DIR "/usr/local/freeswitch/run"
#define SWITCH_LOG_DIR "/usr/local/freeswitch/log"
#define SWITCH_DB_DIR "/usr/local/freeswitch/db"
#define SWITCH_HTDOCS_DIR "/usr/local/freeswitch/htdocs"
#define SWITCH_FONTS_DIR "/usr/local/freeswitch/fonts"
#define SWITCH_SOUNDS_DIR "/usr/local/freeswitch/sounds"
#define SWITCH_GRAMMAR_DIR "/usr/local/freeswitch/grammar"
#define SWITCH_CERTS_DIR "/usr/local/freeswitch/certs"
#define SWITCH_SCRIPT_DIR "/usr/local/freeswitch/scripts"
#define SWITCH_RECORDINGS_DIR "/usr/local/freeswitch/recordings"
#define SWITCH_IMAGES_DIR "/usr/local/freeswitch/images"
#define SWITCH_STORAGE_DIR "/usr/local/freeswitch/storage"
#define SWITCH_CACHE_DIR "/usr/local/freeswitch/cache"
#define SWITCH_CONF_DIR "/usr/local/freeswitch/conf"
#define SWITCH_DATA_DIR "/usr/local/freeswitch"
#define SWITCH_LOCALSTATE_DIR "/usr/local/freeswitch"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
#define DEBUG /**/
#define SIZEOF_LONG 8
#define HAVE_ODBC 1
#define POSTGRESQL_VERSION ""
#define POSTGRESQL_MAJOR_VERSION 
#define POSTGRESQL_MINOR_VERSION 
#define POSTGRESQL_PATCH_VERSION 
#define HAVE_LIBJPEG 1
#define HAVE_DIRENT_H 1
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_RESOURCE_H 1
#define HAVE_SCHED_H 1
#define HAVE_WCHAR_H 1
#define HAVE_SYS_IOCTL_H 1
#define HAVE_SYS_PRCTL_H 1
#define HAVE_SYS_SELECT_H 1
#define HAVE_NETDB_H 1
#define HAVE_SYS_TIME_H 1
#define TIME_WITH_SYS_TIME 1
#define HAVE_STDLIB_H 1
#define HAVE_MALLOC 1
#define RETSIGTYPE void
#define HAVE_STRFTIME 1
#define HAVE_GETHOSTNAME 1
#define HAVE_VASPRINTF 1
#define HAVE_MMAP 1
#define HAVE_MLOCK 1
#define HAVE_MLOCKALL 1
#define HAVE_USLEEP 1
#define HAVE_GETIFADDRS 1
#define HAVE_TIMERFD_CREATE 1
#define HAVE_GETDTABLESIZE 1
#define HAVE_POSIX_OPENPT 1
#define HAVE_POLL 1
#define HAVE_SCHED_SETSCHEDULER 1
#define HAVE_SETPRIORITY 1
#define HAVE_SETRLIMIT 1
#define HAVE_SETGROUPS 1
#define HAVE_INITGROUPS 1
#define HAVE_GETRUSAGE 1
#define HAVE_WCSNCMP 1
#define HAVE_SETGROUPS 1
#define HAVE_ASPRINTF 1
#define HAVE_SETENV 1
#define HAVE_PSELECT 1
#define HAVE_GETTIMEOFDAY 1
#define HAVE_LOCALTIME_R 1
#define HAVE_GMTIME_R 1
#define HAVE_STRCASECMP 1
#define HAVE_DECL_STRERROR_R 1
#define HAVE_STRERROR_R 1
#define STRERROR_R_CHAR_P 1
#define HAVE_SCHED_SETAFFINITY 1
#define HAVE_SCHED_GETAFFINITY 1
#define HAVE_CPU_SET_MACROS 1
#define HAVE_CLOCK_GETTIME 1
#define HAVE_CLOCK_GETRES 1
#define HAVE_CLOCK_NANOSLEEP 1
#define HAVE_PTHREAD_SETSCHEDPARAM 1
#define HAVE_DEV_PTMX 1
#define HAVE_OPENPTY 1
#define HAVE_STRUCT_TM_TM_GMTOFF 1
#define HAVE_STRUCT_TM_TM_ZONE 1
#define HAVE_RLIMIT_MEMLOCK 1
#define HAVE_SCHED_RR 1
#define HAVE_SCHED_FIFO 1
#define USE_MLOCKALL 1
#define USE_SETRLIMIT 1
#define USE_SCHED_SETSCHEDULER 1
#define HAVE_SETENV 1
#define HAVE_STRTOLL 1
#define HAVE_STRTOULL 1
#define HAVE_STRTOQ 1
#define HAVE_STRTOUQ 1
#define SWITCH_BYTE_ORDER __LITTLE_ENDIAN
#define SIZEOF_CHAR 1
#define SIZEOF_INT 4
#define SIZEOF_LONG 8
#define SIZEOF_SHORT 2
#define SIZEOF_LONG_LONG 8
#define SIZEOF_VOIDP 8
#define SIZEOF_SSIZE_T 8
#define SIZEOF_SIZE_T 8
#define HAVE_LIBEDIT 1
#define HAVE_DECL_EL_PROMPT_ESC 1
#define HAVE_DECL_EL_REFRESH 1
#define HAVE_EL_WSET 1
#define HAVE_LIBCRYPTO 1
#define HAVE_LIBSSL 1
#define HAVE_OPENSSL 1
#define HAVE_TLS 1
#define HAVE_OPENSSL_DTLS_SRTP 1
#define HAVE_OPENSSL_DTLS 1
#define HAVE_OPENSSL_DTLSv1_2_method 1
